schoolproject/schoolapp/urls.py
from django .urls import path

from schoolapp import views
app_name='schoolapp'
urlpatterns = [
    path('',views.department,name='department'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('form/',views.form,name='form'),


]

schoolproject/schoolproject/urls.py
from django.contrib import admin
from django.urls import path, include
from schoolproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('schoolapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

schoolproject/schoolapp/models.py
from django.db import models

# Create your models here.
class Depart(models.Model):
    department=models.CharField(max_length=100)
    def __str__(self):
        return self.department

schoolproject/schoolapp/views.py
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render
from .models import Depart

# Create your views here.
def department(request):
    department=Depart.objects.all()
    subject={
        'department':department
    }
    return render(request,"index.html",subject)


def login(request):
    return render(request,'login.html')



def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        conform_password=request.POST['conform_password']
        user=User.objects.create_user(username=username,password=password)
        user.save();
        print("login")
    return render(request,'register.html')
def form(request):
    return render(request,'form.html')

schoolproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >-->
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}
    {% block content %}
    {% endblock %}
</div>





</body>
</html>

schoolproject/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>form</title>
</head>
<body>
<h2>FORM</h2>
<form action="form" method="post"  >
    {% csrf_token %}
<input  type="text" name="username" placeholder="enter user name"><br>
<input type="date" name="date_of_birth" placeholder="enter your date of birth"><br>
<input type="number" name="age" placeholder="enter your age"><br>
 <input type="radio" name="gender"> male
 <input type="radio" name="gender">female<br>
  <input type="number" name="phone number" placeholder="enter your phone number"><br>
    <input type="email" name="email" placeholder="enter your mail id"><br>
    <input  type="text" name="address" placeholder="enter address"><br>
     <label> DEPARTMENT </label>
<select>
<option value = ""> Computer science
</option>
<option value = ""> Commerce
</option>
<option value = ""> Biomathes
</option>
<option value = "">humanities
</option>
<option value = "">Biology science
</select><br>


     <label> COURSES </label>
<select>
<option value = ""> BBA
</option>
<option value = "">BCOM
</option>
<option value = ""> BCA
</option>
<option value = "">MCOM
</option>
<option value = "">MCA

</select><br>

   <label> SELECT YOUR NEEDFUL MATERIAL  </label>

</select><br>
<input type="checkbox"> EXAM PAPPER
<input type="checkbox"> PEN
<input type="checkbox"> pencil
<input type="checkbox"> scale
<input type="checkbox"> rebber<br>

<input  type="submit"><br>

    <a href="{% url 'schoolapp:department' %}" class="btn btn-primary btn-block my_custom_button">home</a>
</form>
</body>
</html>

schoolproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>login</title>
</head>
<body>
<form action="login" method="post">
     {% csrf_token %}
    <input type="text" name="username" placeholder="enter your name"><br>
<input type="password" name="password" placeholder="enter your password"><br>
    <input type="submit">
    <a href="{% url 'schoolapp:form' %}">register</a>

</form>

</body>
</html>

schoolproject/templates/nave.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'shop:allprodcat' %}">home</a>
        </li>
        <li class="nav-item dropdown {% if 'shop' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allprodcat' %}">all products</a></li>
               {% for cat in links %}
            <li><a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a></li>
               {% endfor %}

          </ul>
        </li>
        {% if item_count > 0 %}

        <li class="nav-item">
          <a class="nav-link " href="{% url 'cart:cart_detail' %}" ><i class="fa fa-shopping-cart"></i>({{item_count}})</a>


        </li>
        {% endif %}

      </ul>
      <form class="d-flex" action="{% url 'search_app:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
</nav>

schoolproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
<form action="register" method="post"  >
    {% csrf_token %}
<input  type="text" name="username" placeholder="enter username"><br>
<input type="password" name="password" placeholder="enter the password"><br>
 <input type="password" name="conform_password" placeholder="conform your password"><br>
    <input type="submit">
</form>
</body>
</html>